# Generated by Django 4.1.4 on 2023-09-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='reset_password_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
