# Generated by Django 4.1.4 on 2023-01-17 08:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0001_initial'),
        ('job_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobmodel',
            options={'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='jobtypejobmodel',
            options={'verbose_name_plural': 'Job Type Jobs'},
        ),
        migrations.AlterModelOptions(
            name='jobtypemodel',
            options={'verbose_name_plural': 'Job Types'},
        ),
        migrations.CreateModel(
            name='JobApplicationModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_letter', models.TextField()),
                ('status', models.CharField(default='pending', max_length=100)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_control.applicantmodel')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_control.jobmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
