# Generated by Django 4.1.4 on 2023-06-03 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_control', '0001_initial'),
        ('user_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='user_control.organizationmodel'),
        ),
        migrations.AddField(
            model_name='jobapplicationmodel',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='user_control.applicantmodel'),
        ),
        migrations.AddField(
            model_name='jobapplicationmodel',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='job_control.jobmodel'),
        ),
    ]
