# Generated by Django 4.1.4 on 2023-01-17 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_control', '0002_alter_jobmodel_options_alter_jobtypejobmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplicationmodel',
            options={'verbose_name_plural': 'Job Applications'},
        ),
    ]
