# Generated by Django 4.1.4 on 2023-02-06 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_control', '0003_alter_jobapplicationmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtypejobmodel',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_type', to='job_control.jobtypemodel'),
        ),
    ]
