# Generated by Django 4.1.4 on 2023-02-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_control', '0004_alter_jobtypejobmodel_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='job_types',
            field=models.ManyToManyField(related_name='job_types', to='job_control.jobtypemodel'),
        ),
    ]
