# Generated by Django 4.1.4 on 2023-02-07 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_control', '0005_jobmodel_job_types'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobTypeJobModel',
        ),
    ]
