# Generated by Django 4.1.4 on 2023-06-03 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referencemodel',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='resume_control.resumemodel'),
        ),
        migrations.AddField(
            model_name='personalmodel',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='resume_control.resumemodel'),
        ),
        migrations.AddField(
            model_name='languagemodel',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='resume_control.resumemodel'),
        ),
        migrations.AddField(
            model_name='interestmodel',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest', to='resume_control.resumemodel'),
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='resume_control.resumemodel'),
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='resume_control.resumemodel'),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='resume_control.resumemodel'),
        ),
        migrations.AddField(
            model_name='certificationmodel',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification', to='resume_control.resumemodel'),
        ),
        migrations.AddField(
            model_name='awardmodel',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='resume_control.resumemodel'),
        ),
    ]
