# Generated by Django 4.1.4 on 2023-07-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_control', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagemodel',
            name='proficiency',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Conversational', 'Conversational'), ('Fluent', 'Fluent'), ('Native', 'Native')], default='Basic', max_length=255),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='proficiency',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Beginner', max_length=255, null=True),
        ),
    ]
