# Generated by Django 4.1.4 on 2023-09-10 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_control', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languagemodel',
            old_name='language',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='skillmodel',
            old_name='skill',
            new_name='name',
        ),
    ]
