# Generated by Django 4.1.4 on 2024-03-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_control', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardmodel',
            name='serial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificationmodel',
            name='serial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='serial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='serial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interestmodel',
            name='serial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='languagemodel',
            name='serial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referencemodel',
            name='serial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skillmodel',
            name='serial',
            field=models.IntegerField(default=0),
        ),
    ]
