# Generated by Django 4.1.4 on 2023-09-10 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_control', '0003_rename_language_languagemodel_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interestmodel',
            old_name='interest',
            new_name='name',
        ),
    ]
