# Generated by Django 4.1.4 on 2023-05-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_control', '0003_educationmodel_is_current_experiencemodel_is_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencemodel',
            name='type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Contract', 'Contract'), ('Freelance', 'Freelance'), ('Volunteer', 'Volunteer'), ('Apprenticeship', 'Apprenticeship'), ('Traineeship', 'Traineeship')], default='Full Time', max_length=255),
        ),
    ]
