# Generated by Django 4.1.4 on 2023-06-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_control', '0005_experiencemodel_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencemodel',
            name='company_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
