# Generated by Django 4.1.4 on 2023-06-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_control', '0006_experiencemodel_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationmodel',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
