# Generated by Django 4.1.4 on 2023-06-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_control', '0007_alter_educationmodel_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationmodel',
            name='grade_scale',
            field=models.CharField(default=5.0, max_length=255),
            preserve_default=False,
        ),
    ]
