# Generated by Django 4.1.4 on 2023-06-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_control', '0008_educationmodel_grade_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagemodel',
            name='language',
            field=models.CharField(default='English', max_length=255),
        ),
        migrations.AlterField(
            model_name='languagemodel',
            name='proficiency',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Professional', 'Professional')], default='Professional', max_length=255),
        ),
    ]
