# Generated by Django 4.1.4 on 2023-02-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_control', '0003_optionmodel_question'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionresponsemodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='text_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionresponsemodel',
            name='text_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question (MCQ)'), ('MCQ-M', 'Multiple Choice Question (MCQ-M)'), ('FIB', 'Fill in the Blanks (FIB)'), ('TF', 'True or False (TF)'), ('WA', 'Write Answer (WA)')], default='MCQ', max_length=255),
        ),
        migrations.RemoveField(
            model_name='questionresponsemodel',
            name='answer',
        ),
    ]
