# Generated by Django 4.1.4 on 2023-02-08 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_control', '0004_alter_questionresponsemodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponsemodel',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_option', to='exam_control.optionmodel'),
        ),
    ]
