# Generated by Django 4.1.4 on 2023-02-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_control', '0005_alter_questionresponsemodel_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionresponsemodel',
            name='option',
        ),
        migrations.AddField(
            model_name='questionresponsemodel',
            name='options',
            field=models.ManyToManyField(related_name='response_options', to='exam_control.optionmodel'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question (MCQ)'), ('MCQ-M', 'Multiple Choice Question (MCQ-M)'), ('WA', 'Write Answer (WA)')], default='MCQ', max_length=255),
        ),
    ]
